file = open("sample2.txt", "w+")
file.write("Python File Handling Example")
print("Position after writing:", file.tell())
file.seek(0)
print("Position after seek(0):", file.tell())
file.write("Demo ")
file.flush()
file.seek(0)
print("File Content:", file.read())
file.close()